import { Field } from 'payload'
import {
  createLocationRefField,
  createSharedNeighborhoodsField,
} from '@/shared/location/server/fields'

export const title: Field = {
  name: 'title',
  label: 'Title',
  type: 'text',
  required: true,
  admin: {
    description: 'Main title for the itinerary listicle',
    components: {
      Field: 'src/features/articles/listicle-itineraries/components/field-components/SmartField.tsx',
    },
  },
}

export const location: Field = {
  name: 'location',
  label: 'Location',
  type: 'text',
  required: true,
  admin: {
    description: 'Select the location for this itinerary',
    components: {
      Field: 'src/shared/location/LocationPickerField.tsx',
    },
  },
}

export const locationRef: Field = createLocationRefField()

export const sharedNeighborhoods: Field = createSharedNeighborhoodsField()

export const listTone: Field = {
  name: 'listTone',
  label: 'List Tone',
  type: 'select',
  required: false,
  defaultValue: 'elevated',
  options: [
    { label: 'Elevated', value: 'elevated' },
    { label: 'Casual', value: 'casual' },
    { label: 'Hidden Gem', value: 'hidden-gem' },
    { label: 'Family-Friendly', value: 'family-friendly' },
    { label: 'Date Night', value: 'date-night' },
    { label: 'Budget', value: 'budget' },
  ],
  admin: {
    description: 'Editorial register applied to every blurb and intro generated by AI.',
  },
}

export const step1UiWrapper: Field = {
  type: 'ui',
  name: 'step1_ui_wrapper',
  admin: {
    components: {
      Field: 'src/features/articles/listicle-itineraries/components/layout/Step1Wrapper.tsx',
    },
  },
}
