"""Built-in Day Shell templates for Itinerary Autobuild."""

from __future__ import annotations

from .schemas import DayShell, ShellSlot


BUILT_IN_DAY_SHELLS: dict[str, DayShell] = {
    "full_day_balanced": DayShell(
        id="full_day_balanced",
        name="Full Day Balanced",
        description="Classic full day with two morning anchors, lunch, afternoon, dinner, and nightlife.",
        slots=[
            ShellSlot(
                id="morning_activity",
                label="Morning activity",
                daypart="morning",
                acceptable_collections=["attractions"],
                preferred_collections=["attractions"],
                intent_tags=["landmark", "museum", "culture", "walk", "morning"],
            ),
            ShellSlot(
                id="second_morning_activity",
                label="Second morning activity",
                daypart="morning",
                acceptable_collections=["attractions"],
                preferred_collections=["attractions"],
                intent_tags=["landmark", "neighborhood", "gallery", "market", "morning"],
            ),
            ShellSlot(
                id="lunch",
                label="Lunch",
                daypart="lunch",
                acceptable_collections=["dining"],
                preferred_collections=["dining"],
                intent_tags=["lunch", "restaurant", "local food"],
            ),
            ShellSlot(
                id="afternoon_activity",
                label="Afternoon activity",
                daypart="afternoon",
                acceptable_collections=["attractions"],
                preferred_collections=["attractions"],
                intent_tags=["afternoon", "museum", "tour", "experience", "thing to do"],
            ),
            ShellSlot(
                id="dinner",
                label="Dinner",
                daypart="dinner",
                acceptable_collections=["dining"],
                preferred_collections=["dining"],
                intent_tags=["dinner", "restaurant", "evening meal"],
            ),
            ShellSlot(
                id="nightlife",
                label="Nightlife",
                daypart="nightlife",
                acceptable_collections=["nightlife"],
                preferred_collections=["nightlife"],
                intent_tags=["nightlife", "cocktails", "music", "late night", "bar", "club"],
            ),
        ],
    ),
    "light_full_day": DayShell(
        id="light_full_day",
        name="Light Full Day",
        description="A complete but lower-friction day with late start, lunch, relaxed activity, dinner, and low-key evening.",
        slots=[
            ShellSlot(
                id="late_morning_activity",
                label="Late-morning activity",
                daypart="late_morning",
                acceptable_collections=["attractions"],
                preferred_collections=["attractions"],
                intent_tags=["late morning", "easy", "walk", "museum", "low effort"],
            ),
            ShellSlot(
                id="lunch",
                label="Lunch",
                daypart="lunch",
                acceptable_collections=["dining"],
                preferred_collections=["dining"],
                intent_tags=["lunch", "restaurant", "easy"],
            ),
            ShellSlot(
                id="relaxed_afternoon_activity",
                label="Relaxed afternoon activity",
                daypart="afternoon",
                acceptable_collections=["attractions"],
                preferred_collections=["attractions"],
                intent_tags=["afternoon", "relaxed", "stroll", "gallery", "park"],
                avoid_tags=["strenuous", "all day"],
            ),
            ShellSlot(
                id="dinner",
                label="Dinner",
                daypart="dinner",
                acceptable_collections=["dining"],
                preferred_collections=["dining"],
                intent_tags=["dinner", "restaurant", "comfortable"],
            ),
            ShellSlot(
                id="low_key_evening",
                label="Low-key evening",
                daypart="evening",
                acceptable_collections=["nightlife"],
                preferred_collections=["nightlife"],
                intent_tags=["low key", "cocktails", "lounge", "wine bar", "evening"],
                avoid_tags=["high energy", "club"],
            ),
        ],
    ),
    "food_focused_full_day": DayShell(
        id="food_focused_full_day",
        name="Food-Focused Full Day",
        description="Full day built around coffee, markets, lunch, tastings, dinner, and dessert or drinks.",
        slots=[
            ShellSlot(
                id="breakfast_coffee",
                label="Breakfast or coffee",
                daypart="morning",
                acceptable_collections=["dining"],
                preferred_collections=["dining"],
                intent_tags=["breakfast", "coffee", "cafe", "bakery", "pastry"],
            ),
            ShellSlot(
                id="food_culture_stop",
                label="Market or food-culture stop",
                daypart="morning",
                acceptable_collections=["attractions", "dining"],
                preferred_collections=["attractions"],
                intent_tags=["market", "food culture", "local food", "culinary", "tasting"],
            ),
            ShellSlot(
                id="lunch",
                label="Lunch",
                daypart="lunch",
                acceptable_collections=["dining"],
                preferred_collections=["dining"],
                intent_tags=["lunch", "restaurant", "local specialty"],
            ),
            ShellSlot(
                id="afternoon_food_stop",
                label="Afternoon food or tasting stop",
                daypart="afternoon",
                acceptable_collections=["dining", "attractions"],
                preferred_collections=["dining"],
                intent_tags=["tasting", "snack", "market", "coffee", "cafe", "food hall"],
            ),
            ShellSlot(
                id="dinner",
                label="Dinner",
                daypart="dinner",
                acceptable_collections=["dining"],
                preferred_collections=["dining"],
                intent_tags=["dinner", "restaurant", "fine dining", "tasting menu"],
            ),
            ShellSlot(
                id="dessert_drinks",
                label="Dessert or drinks",
                daypart="evening",
                acceptable_collections=["dining", "nightlife"],
                preferred_collections=["dining"],
                intent_tags=["dessert", "bakery", "ice cream", "gelato", "pastry", "coffee", "cafe", "cocktails", "drinks"],
            ),
        ],
    ),
    "adventure_full_day": DayShell(
        id="adventure_full_day",
        name="Adventure Full Day",
        description="Active day with two morning activities, lunch, two afternoon activities, and dinner.",
        slots=[
            ShellSlot(
                id="morning_activity",
                label="Morning activity",
                daypart="morning",
                acceptable_collections=["attractions"],
                preferred_collections=["attractions"],
                intent_tags=["adventure", "outdoor", "hike", "tour", "active", "morning"],
            ),
            ShellSlot(
                id="second_morning_activity",
                label="Second morning activity",
                daypart="morning",
                acceptable_collections=["attractions"],
                preferred_collections=["attractions"],
                intent_tags=["adventure", "viewpoint", "outdoor", "active", "experience"],
            ),
            ShellSlot(
                id="lunch",
                label="Lunch",
                daypart="lunch",
                acceptable_collections=["dining"],
                preferred_collections=["dining"],
                intent_tags=["lunch", "casual", "refuel", "local food"],
            ),
            ShellSlot(
                id="afternoon_activity",
                label="Afternoon activity",
                daypart="afternoon",
                acceptable_collections=["attractions"],
                preferred_collections=["attractions"],
                intent_tags=["adventure", "afternoon", "tour", "outdoor", "hands on"],
            ),
            ShellSlot(
                id="second_afternoon_activity",
                label="Second afternoon activity",
                daypart="afternoon",
                acceptable_collections=["attractions"],
                preferred_collections=["attractions"],
                intent_tags=["adventure", "view", "active", "experience", "late afternoon"],
            ),
            ShellSlot(
                id="dinner",
                label="Dinner",
                daypart="dinner",
                acceptable_collections=["dining"],
                preferred_collections=["dining"],
                intent_tags=["dinner", "restaurant", "hearty", "comfortable"],
            ),
        ],
    ),
    "nightlife_full_day": DayShell(
        id="nightlife_full_day",
        name="Nightlife Full Day",
        description="Late-start full day weighted toward dinner, social evening stops, and multiple nightlife venues.",
        slots=[
            ShellSlot(
                id="late_start_lunch",
                label="Lunch or late start",
                daypart="lunch",
                acceptable_collections=["dining"],
                preferred_collections=["dining"],
                intent_tags=["lunch", "late start", "brunch", "restaurant"],
            ),
            ShellSlot(
                id="recovery_friendly_activity",
                label="Recovery-friendly afternoon activity",
                daypart="afternoon",
                acceptable_collections=["attractions"],
                preferred_collections=["attractions"],
                intent_tags=["relaxed", "afternoon", "gallery", "walk", "easy", "culture"],
                avoid_tags=["strenuous", "early morning"],
            ),
            ShellSlot(
                id="dinner",
                label="Dinner",
                daypart="dinner",
                acceptable_collections=["dining"],
                preferred_collections=["dining"],
                intent_tags=["dinner", "restaurant", "pre nightlife", "social"],
            ),
            ShellSlot(
                id="evening_social_stop",
                label="Evening drinks, show, or social stop",
                daypart="evening",
                acceptable_collections=["nightlife"],
                preferred_collections=["nightlife"],
                intent_tags=["cocktails", "show", "music", "lounge", "social", "evening"],
            ),
            ShellSlot(
                id="nightlife_stop",
                label="Nightlife stop",
                daypart="nightlife",
                acceptable_collections=["nightlife"],
                preferred_collections=["nightlife"],
                intent_tags=["nightlife", "club", "bar", "music", "high energy"],
            ),
            ShellSlot(
                id="late_night_nightlife",
                label="Late-night nightlife stop",
                daypart="nightlife",
                acceptable_collections=["nightlife"],
                preferred_collections=["nightlife"],
                intent_tags=["late night", "club", "dance", "after hours", "nightlife"],
            ),
        ],
    ),
}


DEFAULT_DAY_SHELL_ID = "full_day_balanced"

