export const IDEAL_FOR_TAGS = [
  "Large Groups & Parties",
  "Birthdays & Celebrations",
  "Breakfast",
  "Brunch",
  "BYOB-Friendly",
  "Casual Dining",
  "Budget-Friendly",
  "Classic & Traditional",
  "Coffee & Light Bites",
  "Business Dining",
  "Date Nights",
  "Afternoon & Daytime Drinks",
  "Solo Dining",
  "Family-Friendly",
  "Tapas & Small Plates",
  "Craft Beer",
  "Craft Cocktails",
  "Wine Bars",
  "Bar Seating",
  "Trendy Hot Spots",
  "Fine Dining",
  "First Dates",
  "Happy Hour",
  "Impressing Visitors",
  "Healthy Eating",
  "Late-Night & Party Scene",
  "Live Music",
  "Lunch",
  "Pre-Theater",
  "Private Dining",
  "Takeout & Delivery",
  "Outdoor Seating",
  "Special Occasions",
  "Experiential Dining",
  "Walk-In Friendly",
  "Sports Bar",
] as const;

export type IdealForTag = typeof IDEAL_FOR_TAGS[number];
