export const IDEAL_FOR_TAGS = [
  "Large Groups & Parties",
  "Birthdays & Celebrations",
  "Breakfast",
  "Brunch",
  "BYOB-Friendly",
  "Casual Dining",
  "Budget-Friendly",
  "Classic & Traditional",
  "Coffee & Light Bites",
  "Business Dining",
  "Date Nights",
  "Afternoon & Daytime Drinks",
  "Solo Dining",
  "Family-Friendly",
  "Tapas & Small Plates",
  "Craft Beer",
  "Craft Cocktails",
  "Wine Bars",
  "Bar Seating",
  "Trendy Hot Spots",
  "Fine Dining",
  "First Dates",
  "Happy Hour",
  "Impressing Visitors",
  "Healthy Eating",
  "Late-Night & Party Scene",
  "Live Music",
  "Lunch",
  "Pre-Theater",
  "Private Dining",
  "Catch-Up Conversations",
  "Friends' Night Out",
  "Late-Night Cravings",
  "Takeout & Delivery",
  "Outdoor Seating",
  "Special Occasions",
  "Experiential Dining",
  "Walk-In Friendly",
  "Sports Bar",
] as const;

export type IdealForTag = typeof IDEAL_FOR_TAGS[number];

export const IDEAL_FOR_TAG_GROUPS = [
  {
    label: "Occasions & Company",
    tags: [
      "Birthdays & Celebrations",
      "Business Dining",
      "Date Nights",
      "Family-Friendly",
      "First Dates",
      "Impressing Visitors",
      "Large Groups & Parties",
      "Pre-Theater",
      "Private Dining",
      "Catch-Up Conversations",
      "Friends' Night Out",
      "Solo Dining",
      "Special Occasions",
    ],
  },
  {
    label: "Meal Moments",
    tags: [
      "Afternoon & Daytime Drinks",
      "Breakfast",
      "Brunch",
      "Coffee & Light Bites",
      "Happy Hour",
      "Late-Night & Party Scene",
      "Late-Night Cravings",
      "Lunch",
    ],
  },
  {
    label: "Dining Style",
    tags: [
      "Budget-Friendly",
      "Casual Dining",
      "Classic & Traditional",
      "Experiential Dining",
      "Fine Dining",
      "Healthy Eating",
      "Tapas & Small Plates",
    ],
  },
  {
    label: "Drinks & Nightlife",
    tags: [
      "Craft Beer",
      "Craft Cocktails",
      "Live Music",
      "Sports Bar",
      "Trendy Hot Spots",
      "Wine Bars",
    ],
  },
  {
    label: "Service & Atmosphere",
    tags: [
      "BYOB-Friendly",
      "Bar Seating",
      "Outdoor Seating",
      "Takeout & Delivery",
      "Walk-In Friendly",
    ],
  },
] as const satisfies readonly {
  label: string;
  tags: readonly IdealForTag[];
}[];
