"""url2blog prompt templates, grouped by domain."""

from .extract import (
    EXTRACT_PROMPT,
    TRANSLATE_PROMPT,
    CLASSIFY_ARTICLE_TYPE_PROMPT,
)
from .cleanup import (
    URL2BLOG_TEXT_CLEANUP_PROMPT,
    URL2BLOG_TEXT_CLEANUP_CHUNK_PROMPT,
)
from .rewrite import (
    SEO_SAFE_CONTENT_GENERATION_GUIDELINES,
    V2_GUIDELINE_REWRITE_PROMPT,
    V2_REWRITE_RETRY_FEEDBACK_SUFFIX,
    V2_REWRITE_REPAIR_PROMPT,
    V2_GUIDELINE_REWRITE_MARKDOWN_PROMPT,
    V2_REWRITE_REPAIR_MARKDOWN_PROMPT,
)
from .audit import (
    V2_QUALITY_AUDIT_PROMPT,
    V2_TITLE_GENERATION_PROMPT,
)
from .facts import (
    V2_SOURCE_FACTS_EXTRACTION_PROMPT,
    V2_FACT_COVERAGE_AUDIT_PROMPT,
    V2_FACT_REPAIR_PROMPT,
    V2_FACT_REPAIR_MARKDOWN_PROMPT,
)
from .length import (
    V2_LENGTH_EXPANSION_PROMPT,
    V2_LENGTH_EXPANSION_MARKDOWN_PROMPT,
)
from .editorial import (
    EDITORIAL_COMPONENT_LABELS,
    V2_EDITORIAL_BLUEPRINT_PROMPT,
    V2_SHORT_ARTICLE_ENRICHMENT_PROMPT,
    V2_EDITORIAL_AUGMENTATION_PROMPT,
)
from .narrative import (
    NARRATIVE_FOCUS_PRESETS,
    V2_NARRATIVE_FOCUS_SELECTION_PROMPT,
)

__all__ = [
    "EXTRACT_PROMPT",
    "TRANSLATE_PROMPT",
    "CLASSIFY_ARTICLE_TYPE_PROMPT",
    "URL2BLOG_TEXT_CLEANUP_PROMPT",
    "URL2BLOG_TEXT_CLEANUP_CHUNK_PROMPT",
    "SEO_SAFE_CONTENT_GENERATION_GUIDELINES",
    "V2_GUIDELINE_REWRITE_PROMPT",
    "V2_REWRITE_RETRY_FEEDBACK_SUFFIX",
    "V2_REWRITE_REPAIR_PROMPT",
    "V2_GUIDELINE_REWRITE_MARKDOWN_PROMPT",
    "V2_REWRITE_REPAIR_MARKDOWN_PROMPT",
    "V2_QUALITY_AUDIT_PROMPT",
    "V2_TITLE_GENERATION_PROMPT",
    "V2_SOURCE_FACTS_EXTRACTION_PROMPT",
    "V2_FACT_COVERAGE_AUDIT_PROMPT",
    "V2_FACT_REPAIR_PROMPT",
    "V2_FACT_REPAIR_MARKDOWN_PROMPT",
    "V2_LENGTH_EXPANSION_PROMPT",
    "V2_LENGTH_EXPANSION_MARKDOWN_PROMPT",
    "EDITORIAL_COMPONENT_LABELS",
    "V2_EDITORIAL_BLUEPRINT_PROMPT",
    "V2_SHORT_ARTICLE_ENRICHMENT_PROMPT",
    "V2_EDITORIAL_AUGMENTATION_PROMPT",
    "NARRATIVE_FOCUS_PRESETS",
    "V2_NARRATIVE_FOCUS_SELECTION_PROMPT",
]
