export const STAGE_ORDER = [
  'stage_0',
  'stage_1',
  'stage_1_quality_gate',
  'stage_1_repair',
  'stage_2',
  'stage_2_quality_gate',
  'stage_2_retry',
  'stage_3_guideline',
  'stage_3_coverage',
  'stage_3_supplement',
  'stage_3',
  'stage_3_quality_gate',
  'stage_3_improve',
  'stage_editorial_gate',
  'stage_editorial_augmentation',
  'stage_editorial_skip',
  'stage_4',
  'stage_5_quality_gate',
  'stage_5_retry',
  'complete',
] as const

export const STAGE_LABELS: Record<string, string> = {
  stage_0: 'Stage 0: Input received',
  stage_1: 'Stage 1: Transcript cleaned',
  stage_1_quality_gate: 'Stage 1 Gate: Transcript quality check',
  stage_1_repair: 'Stage 1 Retry: Transcript repair',
  stage_2: 'Stage 2: Article classified',
  stage_2_quality_gate: 'Stage 2 Gate: Classification confidence check',
  stage_2_retry: 'Stage 2 Retry: Re-classification',
  stage_3_guideline: 'Stage 3A: Guideline retrieval',
  stage_3_coverage: 'Stage 3B: Coverage analysis',
  stage_3_supplement: 'Stage 3C: Supplement generation',
  stage_3: 'Stage 3D: Article composition',
  stage_3_quality_gate: 'Stage 3 Gate: Article quality check',
  stage_3_improve: 'Stage 3 Retry: Article quality rewrite',
  stage_editorial_gate: 'Editorial Gate: Augment or skip',
  stage_editorial_augmentation: 'Editorial: Augmentation applied',
  stage_editorial_skip: 'Editorial: Augmentation skipped',
  stage_4: 'Stage 4: Title generated',
  stage_5_quality_gate: 'Stage 5 Gate: Title quality check',
  stage_5_retry: 'Stage 5 Retry: Title regeneration',
  complete: 'Complete',
}

export const PIPELINE_TIMELINE = [
  { key: 'stage_1', label: '1. Clean Transcript', optional: false },
  { key: 'stage_1_quality_gate', label: '2. Transcript Quality Gate', optional: false },
  { key: 'stage_1_repair', label: '2b. Transcript Repair (If Needed)', optional: true },
  { key: 'stage_2', label: '3. Classify Article Type', optional: false },
  { key: 'stage_2_quality_gate', label: '4. Classification Confidence Gate', optional: false },
  { key: 'stage_2_retry', label: '4b. Re-classify (If Needed)', optional: true },
  { key: 'stage_3_guideline', label: '5. Retrieve Guideline', optional: false },
  { key: 'stage_3_coverage', label: '6. Coverage Analysis', optional: false },
  { key: 'stage_3_supplement', label: '6b. Generate Supplement (If Needed)', optional: true },
  { key: 'stage_3', label: '7. Compose Article', optional: false },
  { key: 'stage_3_quality_gate', label: '8. Article Quality Gate', optional: false },
  { key: 'stage_3_improve', label: '8b. Article Rewrite (If Needed)', optional: true },
  { key: 'stage_editorial_gate', label: '9. Editorial Gate', optional: false },
  { key: 'stage_editorial_augmentation', label: '9b. Editorial Augmentation', optional: true },
  { key: 'stage_editorial_skip', label: '9c. Editorial Skip', optional: true },
  { key: 'stage_4', label: '10. Generate Title', optional: false },
  { key: 'stage_5_quality_gate', label: '11. Title Quality Gate', optional: false },
  { key: 'stage_5_retry', label: '11b. Title Retry (If Needed)', optional: true },
] as const
