"""YouTube2Blog branching and quality policy constants."""

from __future__ import annotations

# Always-strong model policy for YouTube2Blog.
Y2B_PRIMARY_MODEL = "gemini-2.5-flash-lite"

# Retry limits per branch gate.
Y2B_STAGE1_REPAIR_MAX_RETRIES = 2
Y2B_STAGE2_CLASSIFICATION_MAX_RETRIES = 1
Y2B_STAGE5_TITLE_MAX_RETRIES = 1

# Stage 1 transcript quality checks.
Y2B_STAGE1_MIN_CLEANED_CHARS = 400
Y2B_STAGE1_MIN_RETENTION_RATIO = 0.20
Y2B_STAGE1_MEDIUM_TRANSCRIPT_CHAR_THRESHOLD = 12_000
Y2B_STAGE1_MEDIUM_TRANSCRIPT_MIN_RETENTION_RATIO = 0.14
Y2B_STAGE1_MEDIUM_TRANSCRIPT_MAX_RETENTION_RATIO = 0.95
Y2B_STAGE1_LONG_TRANSCRIPT_CHAR_THRESHOLD = 30_000
Y2B_STAGE1_LONG_TRANSCRIPT_MIN_RETENTION_RATIO = 0.08
Y2B_STAGE1_LONG_TRANSCRIPT_MAX_RETENTION_RATIO = 0.98
Y2B_STAGE1_MAX_RETENTION_RATIO = 0.90
Y2B_STAGE1_CHUNKING_CHAR_THRESHOLD = 18_000
Y2B_STAGE1_CHUNK_TARGET_CHARS = 12_000
Y2B_STAGE1_MAX_OUTPUT_TOKENS = 8_192

# Stage 2 classification gate.
Y2B_STAGE2_MIN_CONFIDENCE = 0.70

# Stage 3 article quality gate.
Y2B_STAGE3_QUALITY_MAX_RETRIES = 2
Y2B_STAGE3_MIN_QUALITY_SCORE = 7.4
Y2B_STAGE3_MIN_CRITICAL_DIMENSION_SCORE = 6.0
Y2B_STAGE3_NEAR_PASS_MARGIN = 0.20

# SEO enrichment gate.
Y2B_SEO_MAX_RETRIES = 1
Y2B_SEO_MIN_SCORE = 7.0
Y2B_SEO_NEAR_PASS_MARGIN = 0.20
Y2B_SEO_MAX_FOCUS_OCCURRENCES = 6
Y2B_SEO_MAX_FOCUS_DENSITY = 0.015
Y2B_SEO_MAX_FOCUS_OCCURRENCE_INCREASE = 3

# Stage 5 title quality gate.
Y2B_STAGE5_MIN_TITLE_SCORE = 7.0
Y2B_STAGE5_MIN_TITLE_CHARS = 35
Y2B_STAGE5_MAX_TITLE_CHARS = 95

# Editorial augmentation gate heuristic.
Y2B_EDITORIAL_GATE_MIN_WORDS = 280
Y2B_EDITORIAL_GATE_MIN_PARAGRAPHS = 4
