import { useEffect, useRef } from 'react'
import type { Dispatch, SetStateAction } from 'react'
import type { RelatedItemOption, SingleTypeListicleDraft } from '../../types'
import {
  buildSingleTypeListicleStructuredDataTemplate,
  serializeStructuredDataTemplate,
} from '../services/structured-data-template.service'

type UseAutoStructuredDataParams = {
  draft: SingleTypeListicleDraft | null
  relatedItems: RelatedItemOption[]
  enabled: boolean
  setDraft: Dispatch<SetStateAction<SingleTypeListicleDraft | null>>
}

export function useAutoStructuredData({
  draft,
  relatedItems,
  enabled,
  setDraft,
}: UseAutoStructuredDataParams) {
  const lastAutoStructuredDataRef = useRef('')

  useEffect(() => {
    if (!draft || !enabled) return

    const nextStructuredData = serializeStructuredDataTemplate(
      buildSingleTypeListicleStructuredDataTemplate({
        draft,
        relatedItems,
      }),
    )

    setDraft((current) => {
      if (!current) return current

      const existingStructuredData = current.seoSection.structuredData.trim()
      const lastAutoStructuredData = lastAutoStructuredDataRef.current.trim()
      const hasAutoGeneratedBefore = Boolean(lastAutoStructuredData)
      const isAutoManaged = (
        (!existingStructuredData && !hasAutoGeneratedBefore)
        || existingStructuredData === lastAutoStructuredData
        || existingStructuredData === nextStructuredData
      )

      if (!isAutoManaged) return current

      if (existingStructuredData === nextStructuredData) {
        lastAutoStructuredDataRef.current = nextStructuredData
        return current
      }

      lastAutoStructuredDataRef.current = nextStructuredData
      return {
        ...current,
        seoSection: {
          ...current.seoSection,
          structuredData: nextStructuredData,
        },
      }
    })
  }, [draft, enabled, relatedItems, setDraft])
}
