import { useEffect, useRef } from 'react'
import type { Dispatch, SetStateAction } from 'react'
import type { RelatedItemOption, SingleTypeListicleDraft } from '../../types'
import {
  buildSingleTypeListicleStructuredDataTemplate,
  serializeStructuredDataTemplate,
} from '../services/structured-data-template.service'

type UseAutoStructuredDataParams = {
  draft: SingleTypeListicleDraft | null
  relatedItems: RelatedItemOption[]
  enabled: boolean
  setDraft: Dispatch<SetStateAction<SingleTypeListicleDraft | null>>
}

export function useAutoStructuredData({
  draft,
  relatedItems,
  enabled,
  setDraft,
}: UseAutoStructuredDataParams) {
  const lastAutoStructuredDataRef = useRef('')

  useEffect(() => {
    if (!draft || !enabled) return

    const nextStructuredData = serializeStructuredDataTemplate(
      buildSingleTypeListicleStructuredDataTemplate({
        draft,
        relatedItems,
      }),
    )

    setDraft((current) => {
      if (!current) return current

      const existingStructuredData = current.seoSection.structuredData.trim()

      // A synced-and-clean draft has to stay clean. The template's
      // `dateModified` is Payload's `updatedAt`, which every sync bumps, so
      // regenerating here would rewrite structuredData right after the sync
      // landed and re-raise the "Out of sync" banner the sync just cleared —
      // with a newer timestamp each click, so it could never be cleared. An
      // empty field is still worth filling: that is real new content, and the
      // sync it dirties settles here on the next pass.
      // Checked on `current` rather than `draft`: the hook state that drives
      // the banner lags a render behind and is still stale at this point.
      if (existingStructuredData && current.payloadId && !current.hasUnsyncedPayloadChanges) {
        return current
      }

      const lastAutoStructuredData = lastAutoStructuredDataRef.current.trim()
      const hasAutoGeneratedBefore = Boolean(lastAutoStructuredData)
      const isAutoManaged = (
        (!existingStructuredData && !hasAutoGeneratedBefore)
        || existingStructuredData === lastAutoStructuredData
        || existingStructuredData === nextStructuredData
      )

      if (!isAutoManaged) return current

      if (existingStructuredData === nextStructuredData) {
        lastAutoStructuredDataRef.current = nextStructuredData
        return current
      }

      lastAutoStructuredDataRef.current = nextStructuredData
      return {
        ...current,
        seoSection: {
          ...current.seoSection,
          structuredData: nextStructuredData,
        },
      }
    })
  }, [draft, enabled, relatedItems, setDraft])
}
