export const EDITORIAL_FEATURE_SLOT_COUNTS = [2, 3, 4, 6] as const
export const EDITORIAL_FEATURE_DEFAULT_SLOT_COUNT = 3
export const EDITORIAL_FEATURE_KICKER_MAX = 40
export const EDITORIAL_FEATURE_TITLE_MAX = 100
export const EDITORIAL_FEATURE_DESCRIPTION_MAX = 600
