export const RESERVED_SLUGS: ReadonlySet<string> = new Set([
  'api',
  'admin',
  'dashboard',
  'login',
  'signup',
  'signin',
  'logout',
  'auth',
  'search',
  'sitemap',
  'robots',
  'rss',
  'feed',
  'page',
  'articles',
  'maps',
  'itineraries',
  'tags',
  'hotels',
  'restaurants',
  'assets',
  '_next',
  'media',
  'about',
  'contact',
  'privacy',
  'terms',
  'support',
  'create',
  'edit',
  'featured',
  'trending',
  'home',
  'index',
  'account',
  'profile',
  'settings',
  'users',
  'user',
  'authors',
  'author',
  'static',
  'public',
  'images',
  'img',
  'og',
  'health',
  'status',
  'categories',
  'category',
  'cookies',
  'legal',
  'country',
  'city',
  'region',
  'continent',
  'preview',
  'draft',
  'drafts',
  'revalidate',
  'embed',
  'widget',
  'share',
  '404',
  '500',
  'manifest',
  'favicon',
])

export const ARTICLE_TYPE_SEGMENTS: ReadonlySet<string> = new Set([
  'articles',
  'maps',
  'itineraries',
])

export function isReservedCountrySegment(segment: string, supportedLangs: ReadonlySet<string>): boolean {
  const normalized = segment.toLowerCase()
  if (supportedLangs.has(normalized)) return false
  if (ARTICLE_TYPE_SEGMENTS.has(normalized)) return true
  return RESERVED_SLUGS.has(normalized)
}
